# Generated by Django 5.1.5 on 2025-03-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0003_remove_videofile_mediafile_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='linked_video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captions_media', to='training_data.mediafile'),
        ),
    ]
