# Generated by Django 5.1.5 on 2025-02-28 15:24

import apps.training_data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0003_remove_videofile_mediafile_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiosegment',
            old_name='source_video',
            new_name='source_audio',
        ),
        migrations.RemoveField(
            model_name='audiosegment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='audiosegment',
            name='sampling_rate',
        ),
        migrations.RemoveField(
            model_name='audiosegment',
            name='speaker_id',
        ),
        migrations.RemoveField(
            model_name='audiosegment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='audiosegment',
            name='transcription',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='metadata_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.training_data.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='split',
            field=models.CharField(blank=True, choices=[('train', 'train'), ('test', 'test'), ('val', 'val')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='linked_video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captions_media', to='training_data.mediafile'),
        ),
    ]
