# Generated by Django 5.1.5 on 2025-03-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0005_rename_source_video_audiosegment_source_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='linked_video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_media', to='training_data.mediafile'),
        ),
    ]
