# Generated by Django 5.1.5 on 2025-02-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0006_alter_mediafile_linked_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='metadata_file',
            new_name='_metadata_file',
        ),
    ]
