# Generated by Django 5.1.5 on 2025-03-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0007_rename_metadata_file_mediafile__metadata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='linked_video_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_media', to='training_data.mediafile', verbose_name='Link File Here'),
        ),
    ]
