# Generated by Django 5.1.7 on 2025-03-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0004_alter_mediafile_linked_video_file'),
        ('training_data', '0008_alter_mediafile_linked_video_file'),
    ]

    operations = [
    ]
