# Generated by Django 5.1.7 on 2025-03-20 21:39

import apps.training_data.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0009_merge_20250320_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='linked_video_file',
        ),
        migrations.AddField(
            model_name='audiosegment',
            name='segment_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/local_media'), upload_to=apps.training_data.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='processed_audio_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.training_data.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='linked_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_caption_file', to='training_data.mediafile', verbose_name='Link Source File Here'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('audio', 'Audio'), ('ass', 'Caption')], max_length=50, null=True),
        ),
    ]
