# Generated by Django 5.1.7 on 2025-03-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0009_merge_20250320_1318'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='mediafile',
        #     name='linked_video_file',
        #     field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_media', to='training_data.mediafile', verbose_name='Link File Here'),
        # ),
    ]
