# Generated by Django 5.1.7 on 2025-03-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0010_alter_mediafile_linked_video_file'),
        ('training_data', '0010_remove_mediafile_linked_video_file_and_more'),
    ]

    operations = [
    ]
