# Generated by Django 5.1.7 on 2025-03-28 14:16

import apps.training_data.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0011_merge_20250328_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosegment',
            name='segment_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sherryyu/ArtFair/core-api/local_media'), upload_to=apps.training_data.models.get_upload_path),
        ),
    ]
