# Generated by Django 5.1.7 on 2025-03-28 15:35

import apps.training_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0012_alter_audiosegment_segment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiosegment',
            old_name='segment_file',
            new_name='segment_file_local',
        ),
        migrations.AddField(
            model_name='audiosegment',
            name='segment_file_remote',
            field=models.FileField(blank=True, null=True, upload_to=apps.training_data.models.get_upload_path),
        ),
    ]
