# Generated by Django 5.1.7 on 2025-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0013_rename_segment_file_audiosegment_segment_file_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='is_source_file',
            field=models.BooleanField(default=False),
        ),
    ]
