# Generated by Django 5.1.7 on 2025-04-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0014_mediafile_is_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='license_content_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
