# Generated by Django 5.1.7 on 2025-04-09 14:33

import apps.training_data.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0015_mediafile_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosegment',
            name='segment_file_local',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/rehmat/Desktop/MS/core-api/local_media'), upload_to=apps.training_data.models.get_upload_path),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('primary_language', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_files', models.ManyToManyField(blank=True, related_name='speakers', to='training_data.mediafile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
