# Generated by Django 5.1.7 on 2025-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0016_alter_audiosegment_segment_file_local_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='video_duration',
            field=models.CharField(blank=True, help_text='Length of the video in HH:MM:SS format', max_length=50, null=True),
        ),
    ]
