# Generated by Django 5.1.7 on 2025-04-15 19:48

import apps.training_data.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0016_alter_audiosegment_segment_file_local_speaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ('name', '-created_at')},
        ),
        migrations.AlterField(
            model_name='audiosegment',
            name='segment_file_local',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sherryyu/ArtFair/core-api/local_media'), upload_to=apps.training_data.models.get_upload_path),
        ),
    ]
