# Generated by Django 5.1.7 on 2025-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0017_alter_speaker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speaker_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
