# Generated by Django 5.1.7 on 2025-04-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0017_mediafile_video_duration'),
        ('training_data', '0018_alter_speaker_speaker_id'),
    ]

    operations = [
    ]
