# Generated by Django 5.1.7 on 2025-04-23 15:38

from django.db import migrations


def forwards(apps, schema_editor):
    CustomUser   = apps.get_model("users", "CustomUser")   # adjust app label
    Channel      = apps.get_model("training_data", "Channel")
    ChannelMember= apps.get_model("training_data", "ChannelMember")
    MediaFile    = apps.get_model("training_data", "MediaFile")

    for user in CustomUser.objects.all():
        brand = (user.brand_name or "").strip()
        if not brand:
            # skip users without a brand – you can decide to give them a default later
            continue

        channel, created = Channel.objects.get_or_create(title=brand)
        ChannelMember.objects.get_or_create(
            channel=channel,
            user=user
        )

        # attach every MediaFile the user already owns
        MediaFile.objects.filter(owner=user, channel__isnull=True)\
                        .update(channel=channel)

def backwards(apps, schema_editor):
    # Danger-free backwards: just keep data, don’t delete anything
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0020_channel_alter_audiosegment_segment_file_local_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]